/*
 * Parity test: planner.js output must match Python planner.py exactly.
 *
 * Reads web/golden.json (generated by web/gen_golden.py against the real
 * Python planner) and independently recomputes every scenario with planner.js,
 * also re-deriving the available-effects dictionary from the raw data.
 *
 * Run:  node web/test_parity.js
 */
"use strict";
const fs = require("fs");
const path = require("path");
const assert = require("assert");
const Planner = require("./planner.js");

const DATA_PATH = path.join(__dirname, "data", "eql_focus_effects.json");
const GOLDEN_PATH = path.join(__dirname, "golden.json");

const CLASSES = Object.keys(Planner.CLASSES);
const TRIOS = [];
(function combos() {
    for (let i = 0; i < CLASSES.length; i++) {
        for (let j = i + 1; j < CLASSES.length; j++) {
            for (let k = j + 1; k < CLASSES.length; k++) {
                TRIOS.push([CLASSES[i], CLASSES[j], CLASSES[k]]);
            }
        }
    }
})();
function trioKey(t) { return t.slice().sort().join("/"); }

function buildEffects(data, trio) {
    const items = Planner.class_filter(data, trio);
    let effects = Planner.focus_effects_available(data, items, trio);
    effects = Planner.max_rank_per_family(effects);
    return effects;
}

function sortedNames(effects) {
    return Object.keys(effects).sort(function (a, b) {
        const cA = effects[a].category;
        const cB = effects[b].category;
        if (cA < cB) return -1;
        if (cA > cB) return 1;
        return a < b ? -1 : a > b ? 1 : 0;
    });
}

function sortedRows(plan) {
    return plan.slice().sort(function (a, b) {
        const rA = a[2] || "";
        const rB = b[2] || "";
        if (rA !== rB) return rA < rB ? -1 : 1;
        return a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0;
    });
}

function statsPayload(stats) {
    return {
        total: stats.total,
        placed: stats.placed,
        restricted: stats.restricted,
        conflicts: stats.conflicts,
        procs: stats.procs,
        not_honored: stats.not_honored,
        clashes: stats.clashes,
        why_here: stats.why_here,
    };
}

function runScenario(data, sc) {
    const trio = sc.trio;
    const effects = buildEffects(data, trio);
    const out = Planner.optimize_plan(
        effects, sc.chosen.slice(), trio,
        sc.forced && JSON.parse(JSON.stringify(sc.forced)),
        sc.gear_ok && JSON.parse(JSON.stringify(sc.gear_ok)),
        sc.any_slots && JSON.parse(JSON.stringify(sc.any_slots)),
    );
    return sortedRows(out.plan);
}

let passed = 0;

function canon(v) {
    if (Array.isArray(v)) return v.map(canon);
    if (v !== null && typeof v === "object") {
        const keys = Object.keys(v).sort();
        const out = {};
        for (const k of keys) out[k] = canon(v[k]);
        return out;
    }
    return v;
}

function eq(a, b) {
    return JSON.stringify(canon(a)) === JSON.stringify(canon(b));
}

function check(cond, msg) {
    if (cond) { passed++; return; }
    throw new Error("FAIL: " + msg);
}

const data = JSON.parse(fs.readFileSync(DATA_PATH, "utf8"));
const golden = JSON.parse(fs.readFileSync(GOLDEN_PATH, "utf8"));

console.log("trio count sanity: " + TRIOS.length);

// availability parity on the two golden-annotated trios
for (const key of Object.keys(golden.effects_available)) {
    const trio = key.split("/");
    const effects = buildEffects(data, trio);
    const got = Object.keys(effects).sort();
    const want = golden.effects_available[key];
    check(JSON.stringify(got) === JSON.stringify(want),
        "effects availability " + key + " ->\n  want " + want.length + "\n  got  " + got.length);
    console.log("effects availability " + key + " OK (" + got.length + ")");
}

// full scenario parity
for (const sc of golden.scenarios) {
    const trio = sc.trio.slice().sort();
    const effects = buildEffects(data, trio);
    const result = Planner.optimize_plan(
        effects,
        sc.chosen.slice(),
        trio.slice(),
        sc.forced && JSON.parse(JSON.stringify(sc.forced)),
        sc.gear_ok && JSON.parse(JSON.stringify(sc.gear_ok)),
        sc.any_slots && JSON.parse(JSON.stringify(sc.any_slots)),
    );
    const gotPlan = sortedRows(result.plan);
    const expectPlan = sc.plan;
    const gotStats = statsPayload(result.stats);
    const expectStats = sc.stats;

    const key = trioKey(trio) + (sc.forced ? "+forced" : "") +
        (sc.gear_ok ? "+gear" : "") + (sc.any_slots ? "+any" : "");
    check(eq(gotPlan, expectPlan),
        "plan " + key + "\n  want " + JSON.stringify(expectPlan) +
        "\n  got  " + JSON.stringify(gotPlan));
    check(eq(gotStats, expectStats),
        "stats " + key + "\n  want " + JSON.stringify(expectStats) +
        "\n  got  " + JSON.stringify(gotStats));
    console.log("scenario " + key + " OK  placed=" + gotStats.placed +
        "/" + gotStats.total);
}

console.log("\nALL PARITY CHECKS PASSED (" + passed + " assertions, " +
    golden.scenarios.length + " scenarios)");